version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: car-history-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-car_history}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: car-history-server
    env_file:
      - .development.env
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-car_history}?sslmode=disable
    depends_on:
      - db

volumes:
  postgres_data:
